version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words:
  - конфигами
  - asyncio
  - Docstrings
  - fastapi
  - loguru
  - psutil
  - pydantic
  - Pydantic
  - pytest
  - pythonpath
  - pywin
  - TDEADLOCK
  - testpaths
  - uvicorn
  - venv
ignoreWords: []
import: []
